blank_issues_enabled: false
contact_links:
  - name: 🛡 Code of Conduct
    url: https://github.com/armirage/.github/blob/master/CODE_OF_CONDUCT.md
    about: By interacting with this repository, organization, or community you agree to abide by terms set forth in the Code of Conduct.
